apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-app
  namespace: petclinic
  labels:
    app: petclinic-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic-app
  template:
    metadata:
      labels:
        app: petclinic-app
    spec:
      containers:
      - image: {{dockerhubuser}}/petclinic:{{BUILD_NUMBER}}
        name: petclinic-app
        args:
          - "java"
          - "-jar"
          - "-Dspring.datasource.url=jdbc:mysql://mysql/petclinic"
          - "-Dspring.profiles.active={{db_profile}}"
          - "petclinic.jar"
---
apiVersion: v1
kind: Service
metadata:
  name: petclinic-app
  namespace: petclinic
spec:
  selector: 
    app: petclinic-app
  type: NodePort
  ports:
      - port: 8080

