apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-app
  namespace: petclinic
  labels:
    run: petclinic-app
spec:
  replicas: 2
  selector:
    matchLabels:
      run: petclinic-app
  template:
    metadata:
      labels:
        run: petclinic-app
    spec:
      containers:
      - image: {{dockerhubuser}}/petclinic:{{BUILD_NUMBER}}
        name: petclinic-app
        args:
          - "java"
          - "-jar"
          - "petclinic.jar"
        ports:
        - containerPort: 8080

