apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: petclinic-app
  namespace: petclinic
spec:
  rules:
    - http:
       paths:
         - path: /
           backend:
             serviceName: petclinic-app
             servicePort: 8080